appName: xds-server
image: xds-server
tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 128Mi

service:
  ports:
    - name: mgmt
      port: 18000

rel:
  component: xds-server
